name: YDMS Build
run-name: YDMS Build and NuGet publish.

on:
  push

jobs:
  cmake-build:
    uses: Yellow-Dog-Man/composite-actions-templates/.github/workflows/cmake-build.yml@main
    with:
      artifact_name: sdl-ydms
