name: YDMS Release Builds

on:
  release:
    types:
      - published
  push:

jobs:
  build-linux:
    strategy:
      matrix:
        include:
          - osver: ubuntu-latest
            image: registry.gitlab.steamos.cloud/steamrt/sniper/sdk
          - osver: ubuntu-24.04-arm
            image: registry.gitlab.steamos.cloud/steamrt/sniper/sdk/arm64


    runs-on: ${{ matrix.osver }}
    container:
      image: ${{ matrix.image }}

    steps:
      - uses: actions/checkout@v4

      - name: Set dist name
        run: |
          if ${{ matrix.osver == 'ubuntu-24.04-arm' }}; then
            echo "distname=sdl-linux-arm" >> "$GITHUB_ENV"
          else
            echo "distname=sdl-linux" >> "$GITHUB_ENV"
          fi

      - name: Create build dirs
        run: |
          mkdir build
          cd build
          echo "builddir=$(pwd)" >> "$GITHUB_ENV"

      - name: 'Install Linux dependencies'
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
            gnome-desktop-testing libasound2-dev libpulse-dev libaudio-dev libjack-dev libsndio-dev \
            libusb-1.0-0-dev libx11-dev libxext-dev libxrandr-dev libxcursor-dev libxfixes-dev libxi-dev \
            libxss-dev libwayland-dev libxkbcommon-dev libdrm-dev libgbm-dev libgl1-mesa-dev libgles2-mesa-dev \
            libegl1-mesa-dev libdbus-1-dev libibus-1.0-dev libudev-dev fcitx-libs-dev

      - name: Build SDL
        working-directory: ${{ env.builddir }}
        run: |
          cmake -DCMAKE_BUILD_TYPE=Release ..
          make -j4

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.distname }}
          path: ${{ env.builddir }}/**/*.so

  build-win:
    runs-on: windows-2025

    steps:
      - uses: actions/checkout@v4

      - name: 'Build archives'
        run: |
          cmake -B build -S .
          cmake --build build --config Release

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows
          path: 'build/**/*.dll'
